run_name: test-converted-ckpt-2nodes
seed: 6198
dry_run: false
no_pre_train_checkpoint: false

wandb:
  project: "Pretrain-OLMoE"   # Name of your W&B project
  entity: "aditi-khandelwal-mcgill-university"  # W&B entity (usually your username or team name)
  group: "aditi-khandelwal-mcgill-university"      # (Optional) Group name for multiple runs
  name: "en-hi-pretrain"               # (Optional) Custom name for this run
  tags: ["experiment1"]  # (Optional) Tags for filtering runs
  rank_zero_only: true 

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 1
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: true
  include_bias: false
  block_type: moe
  layer_norm_type: rms
  layer_norm_with_affine: true
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0
  pad_token_id: 1
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3
  moe_top_k: 8
  moe_num_experts: 64
  moe_dropless: true
  moe_mlp_impl: sparse
  moe_zloss_weight: 0.001
  moe_loss_weight: 0.01

compile: null

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  eps: 1.0e-8
  weight_decay: 0.1
  decay_norm_and_bias: true
  decay_embeddings: true
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 5

scheduler:
  name: cosine_with_warmup
  units: tokens
  t_warmup: 10485760000
  t_max: 5e12
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right

save_folder: /home/mila/k/khandela/scratch/ai2-llm/runs/${run_name}
remote_save_folder: null
save_overwrite: true

save_interval: 3
save_interval_ephemeral: null
save_num_checkpoints_to_keep: -1
sharded_checkpointer: olmo_core

save_interval_unsharded: 3
save_num_unsharded_checkpoints_to_keep: -1

load_path: /home/mila/k/khandela/scratch/ai2-llm/runs/test-converted-ckpt-2nodes/step2/

max_duration: 5ep
global_train_batch_size: 1024
device_train_microbatch_size: 2

precision: amp_bf16
distributed_strategy: fsdp

fsdp:
  wrapping_strategy: by_block
  precision: mixed
  sharding_strategy: FULL_SHARD

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

eval_interval: 20
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  - label: validation-test
    data:
      num_workers: 0
      drop_last: true
      datasets:
        dolma_books-validation:
          - /home/mila/k/khandela/scratch/olmoe-data/test/part-1-00000.npy
        wikitext_103-validation:
          - /home/mila/k/khandela/scratch/olmoe-data/part-2-00000.npy

  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: mmlu_social_sciences_mc_5shot
    type: downstream

data:
  pad_direction: right
  num_workers: 32
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  timeout: 0
  instance_filter:
      repetition_max_period: 13
      repetition_min_period: 1
      repetition_max_count: 32  
  paths:
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-0-00000.npy





