run_name: pretrain-multilingual-en-hi-ar-ru-zh-nolbl
seed: 6198
dry_run: false
no_pre_train_checkpoint: false

wandb:
  project: "Pretrain-OLMoE-No-LBL"   # Name of your W&B project
  entity: "aditi-khandelwal-mcgill-university"  # W&B entity (usually your username or team name)
  group: "aditi-khandelwal-mcgill-university"      # (Optional) Group name for multiple runs
  name: "pretrain-multilingual-en-hi-ar-ru-zh-no-lbl"               # (Optional) Custom name for this run
  tags: ["experiment1"]  # (Optional) Tags for filtering runs
  rank_zero_only: true 

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 1
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: true
  include_bias: false
  block_type: moe
  layer_norm_type: rms
  layer_norm_with_affine: true
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0
  pad_token_id: 1
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3
  moe_top_k: 8
  moe_num_experts: 64
  moe_dropless: true
  moe_mlp_impl: sparse
  moe_zloss_weight: 0.001
  moe_loss_weight: 0.0

compile: null

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  eps: 1.0e-8
  weight_decay: 0.1
  decay_norm_and_bias: true
  decay_embeddings: true
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 25

scheduler:
  name: cosine_with_warmup
  units: tokens
  t_warmup: 10485760000
  t_max: 5e12
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right

save_folder: /home/mila/k/khandela/scratch/ai2-llm/runs/${run_name}
remote_save_folder: null
save_overwrite: true

save_interval: 100
save_interval_ephemeral: null
save_num_checkpoints_to_keep: 2
sharded_checkpointer: olmo_core

save_interval_unsharded: 100
save_num_unsharded_checkpoints_to_keep: 2

load_path: /home/mila/k/khandela/scratch/ai2-llm/runs/pretrain-multilingual-en-hi-ar-ru-zh-nolbl/latest
try_load_latest_save: true

max_duration: 5ep
global_train_batch_size: 1024
device_train_microbatch_size: 2

precision: amp_bf16
distributed_strategy: fsdp

fsdp:
  wrapping_strategy: by_block
  precision: mixed
  sharding_strategy: FULL_SHARD

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

eval_interval: 100
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  - label: validation-test
    data:
      num_workers: 0
      drop_last: true
      datasets:
        arabic-validation:
          - /home/mila/k/khandela/scratch/olmoe-data/test/ar/part-0-00000.npy
        russian-validation:
          - /home/mila/k/khandela/scratch/olmoe-data/test/ru/part-0-00000.npy
        chinese-validation:
          - /home/mila/k/khandela/scratch/olmoe-data/test/zh/part-0-00000.npy
        hindi-validation:
          - /home/mila/k/khandela/scratch/olmoe-data/test/hi/part-0-00000.npy
        english-validation:
          - /home/mila/k/khandela/scratch/olmoe-data/test/en/part-0-00000.npy

  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: mmlu_social_sciences_mc_5shot
    type: downstream

data:
  pad_direction: right
  num_workers: 32
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  timeout: 0
  instance_filter:
      repetition_max_period: 13
      repetition_min_period: 1
      repetition_max_count: 32  
  paths:
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-00-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-00-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-01-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-02-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-02-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-03-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-04-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-04-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-05-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-06-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-06-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-07-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-08-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-08-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-09-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-10-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-10-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-11-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-11-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-12-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-13-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-13-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-14-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-15-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-15-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-16-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-17-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-17-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-18-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-19-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-19-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-20-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-21-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-21-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-22-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-22-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-23-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-24-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-24-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-25-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-26-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-26-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-27-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-28-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-28-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-29-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-30-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-30-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-31-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-31-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-32-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-33-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-33-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-34-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-35-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-35-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-36-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-37-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-37-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-38-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-39-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-39-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-40-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-41-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-41-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-42-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-42-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-43-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-44-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-44-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-45-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-46-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-46-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-47-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-48-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-48-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-49-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-50-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-50-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-51-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-52-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-52-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-53-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-53-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-54-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-55-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-55-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-56-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-57-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-57-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-58-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-59-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-59-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-60-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-61-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-61-00001.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-62-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-63-00000.npy
    - /home/mila/k/khandela/scratch/olmoe-data/multilang/part-63-00001.npy







