run_name: olmo-7b-instruct
image: mosaicml/pytorch:2.1.0_cu121-python3.10-ubuntu20.04
gpu_num: 64
cluster: r12z3
gpu_type: a100_40gb
integrations:
  - integration_type: git_repo
    git_repo: allenai/LLM
    git_branch: epwalsh/tulu-fine-tune
    pip_install: -e .
    ssh_clone: true
command: |-
  cd LLM

  pip freeze

  # Prepare environment.
  mkdir -p /root/.cache/torch/
  mkdir /root/checkpoint/
  mkdir /root/.aws
  touch /root/.aws/credentials
  echo '[s3]' >> /root/.aws/credentials
  echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> /root/.aws/credentials
  echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> /root/.aws/credentials
  echo '' >> /root/.aws/credentials
  echo '[r2]' >> /root/.aws/credentials
  echo "aws_access_key_id = ${R2_ACCESS_KEY_ID}" >> /root/.aws/credentials
  echo "aws_secret_access_key = ${R2_SECRET_ACCESS_KEY}" >> /root/.aws/credentials

  export S3_PROFILE=s3
  export R2_PROFILE=r2
  export OMP_NUM_THREADS=8
  export LOG_FILTER_TYPE=local_rank0_only

  # Download checkpoint (everything except optimizer state).
  aws s3 cp \
    --profile=r2 \
    --endpoint-url https://a198dc34621661a1a66a02d6eb7c4dc3.r2.cloudflarestorage.com \
    s3://olmo-checkpoints/ai2-llm/olmo-medium/svtto91c/step456000-unsharded/config.yaml \
    /root/checkpoint/
  aws s3 cp \
    --profile=r2 \
    --endpoint-url https://a198dc34621661a1a66a02d6eb7c4dc3.r2.cloudflarestorage.com \
    s3://olmo-checkpoints/ai2-llm/olmo-medium/svtto91c/step456000-unsharded/train.pt \
    /root/checkpoint/
  aws s3 cp \
    --profile=r2 \
    --endpoint-url https://a198dc34621661a1a66a02d6eb7c4dc3.r2.cloudflarestorage.com \
    s3://olmo-checkpoints/ai2-llm/olmo-medium/svtto91c/step456000-unsharded/model.pt \
    /root/checkpoint/

  torchrun \
  --master_addr $MASTER_ADDR \
  --master_port $MASTER_PORT \
  --nnodes $NUM_NODES \
  --node_rank $NODE_RANK \
  --nproc_per_node 8 \
  scripts/train.py configs/mitchish-instruct.yaml \
    --run_name=mitchish-instruct \
    --save_overwrite \
    --wandb.name=mitchish-lumi-instruct \
    --time_limit=169200 \
    --load_path=/root/checkpoint \
    --reset_optimizer_state \
    --reset_trainer_state
