name: olmo-small-test
image: mosaicml/pytorch:2.1.0_cu121-python3.10-ubuntu20.04
compute:
  #cluster: r12z3
  cluster: r7z2
  gpus: 8
  gpu_type: a100_40gb
integrations:
  - integration_type: git_repo
    git_repo: allenai/LLM
    git_branch: epwalsh/lr-schedule-tokens
    pip_install: -e .
    ssh_clone: true
command: |-
  run_name=mitchish-small-test

  cd LLM

  pip freeze

  # Prepare environment including AWS config files for both S3 and R2 access.
  mkdir -p /root/.cache/torch

  torchrun \
  --master_addr "$MASTER_ADDR" \
  --master_port "$MASTER_PORT" \
  --nnodes "$NUM_NODES" \
  --node_rank "$NODE_RANK" \
  --nproc_per_node 8 \
  scripts/train.py configs/small-test-s3.yaml \
    --run_name=${run_name}
