name: olmo-small-test
image: mosaicml/pytorch:2.1.0_cu121-python3.10-ubuntu20.04
compute:
  #cluster: r12z3
  cluster: r7z2
  gpus: 8
  gpu_type: a100_40gb
integrations:
  - integration_type: git_repo
    git_repo: allenai/LLM
    git_branch: epwalsh/lr-schedule-tokens
    pip_install: -e .
    ssh_clone: true
command: |-
  run_name=mitchish-small-test

  cd LLM

  pip freeze

  # Prepare environment.
  mkdir -p /root/.cache/torch
  export OMP_NUM_THREADS=8
  export LOG_FILTER_TYPE=local_rank0_only

  torchrun --nproc_per_node 8 scripts/train.py configs/small-test-s3.yaml \
    --run_name=${run_name}
