run_name: tiny-run-001
seed: 6198
dry_run: false

model:
  d_model: 256
  n_heads: 4
  n_layers: 5
  mlp_ratio: 4
  alibi: true
  alibi_bias_max: 8.0
  flash_attention: false
  attention_dropout: 0.0
  attention_layer_norm: false
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 256
  include_bias: true
  vocab_size: 50257
  eos_token_id: 50256
  pad_token_id: 50256
  init_device: null
  init_std: 0.02

optimizer:
  name: lionw
  learning_rate: 3.0e-4
  weight_decay: 0.01
  betas:
  - 0.9
  - 0.95

scheduler:
  name: cosine_with_warmup
  t_warmup: 100
  alpha_f: 0.1

data:
  paths: ${path.glob:${path.choose:${oc.env:SCRATCH_DIR,no_exist}/pretraining_data/preprocessed,/net/nfs.cirrascale/allennlp/llm-data}/c4/en/c4-train.*.npy}
  pad_direction: right
  num_workers: 2
  drop_last: true
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  timeout: 0

eval_interval: 50
evaluators:
  - label: c4-validation
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: 5
    data:
      paths: ${path.glob:${path.choose:${oc.env:SCRATCH_DIR,no_exist}/pretraining_data/preprocessed,/net/nfs.cirrascale/allennlp/llm-data}/c4/en/c4-validation.*.npy}
      pad_direction: right
      num_workers: 4
      drop_last: true
      pin_memory: true
      prefetch_factor: 4  # bump to 16 if on LUMI
      persistent_workers: true
      timeout: 0
  - label: piqa
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: hellaswag
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: winogrande
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: openbook_qa
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: sciq
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: arc_easy
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: copa
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: rte
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: commitment_bank
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: mrpc
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}
  - label: sst2
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: ${downstream_eval_subset_num_batches}
    is_downstream: true
    data: ${downstream_eval_data_config}

tokenizer:
  identifier: gpt2
  truncate_direction: right

save_folder: ${path.choose:${oc.env:SCRATCH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
save_interval: 1000
save_num_checkpoints_to_keep: 2
save_overwrite: true

load_path: null

max_duration: 1708984  # 7B tokens
global_train_batch_size: 16
device_train_microbatch_size: 4
downstream_eval_subset_num_batches: 10  # a small number is probably enough

downstream_eval_data_config:
  pad_direction: right
  num_workers: 4
  drop_last: false
  pin_memory: true
  prefetch_factor: 4  # bump to 16 if on LUMI
  persistent_workers: true
  timeout: 0

precision: fp32

wandb: null
#   name: ${run_name}

speed_monitor:
  window_size: 20

console_log_interval: 10
