run_name: c4-large-run-001
seed: 6198
dry_run: false

wandb:
  name: ${run_name}

model:
  d_model: 8192
  n_heads: 32
  n_layers: 64
  mlp_ratio: 8
  alibi: true
  alibi_bias_max: 8.0
  attention_dropout: 0.0
  attention_layer_norm: true
  multi_query_attention: true
  block_type: parallel
  layer_norm_type: default  # if not compiling, use 'low_precision'
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50257
  eos_token_id: 50256
  pad_token_id: 50256
  init_device: meta
  init_std: 0.02

compile: null  # currently this doesn't work with activation checkpointing
#compile:
#  mode: default

activation_checkpointing: true

optimizer:
  name: decoupled_lionw
  learning_rate: 8.0e-5
  weight_decay: 4.0e-5
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08

scheduler:
  name: cosine_with_warmup
  t_warmup: 100
  alpha_f: 0.1

data:
  paths: ${path.glob:${path.choose:${oc.env:SCRATCH_DIR,no_exist}/pretraining_data/preprocessed,/net/nfs.cirrascale/allennlp/llm-data}/c4/en/c4-train.*.npy}
  pad_direction: right
  num_workers: 4
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0

eval_interval: ${save_interval}
evaluators:
  - label: c4-validation
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: 5
    data:
      paths: ${path.glob:${path.choose:${oc.env:SCRATCH_DIR,no_exist}/pretraining_data/preprocessed,/net/nfs.cirrascale/allennlp/llm-data}/c4/en/c4-validation.*.npy}
      pad_direction: right
      num_workers: 4
      drop_last: true
      pin_memory: true
      prefetch_factor: 16
      persistent_workers: true
      timeout: 0

tokenizer:
  identifier: gpt2
  truncate_direction: right

max_duration: 476837  # 2T tokens

save_folder: ${path.choose:${oc.env:FLASH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
save_interval: 2000
save_num_checkpoints_to_keep: -1
save_overwrite: false

load_path: null

global_train_batch_size: 2048
device_train_microbatch_size: 4

precision: amp_bf16

max_grad_norm: 1.0

speed_monitor:
  window_size: 20
