run_name: c4-tiny-run-001
seed: 6198
dry_run: false

wandb:
  name: ${run_name}
  log_interval: ${console_log_interval}

model:
  d_model: 1024
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  alibi: true
  alibi_bias_max: 8.0
  flash_attention: false
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: true
  block_type: sequential
  layer_norm_type: default  # if not compiling, use 'low_precision'
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 1024
  include_bias: true
  vocab_size: 50257
  embedding_size: 50304
  eos_token_id: 50256
  pad_token_id: 50256
  init_device: meta
  init_std: 0.02

compile:
  mode: default

optimizer:
  name: decoupled_lionw
  learning_rate: 3.0e-4
  weight_decay: 1.5e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08

scheduler:
  name: cosine_with_warmup
  t_warmup: 100
  alpha_f: 0.1

data:
  paths: ${path.glob:${path.choose:${oc.env:SCRATCH_DIR,no_exist}/pretraining_data/preprocessed,/net/nfs.cirrascale/allennlp/llm-data}/c4/en/c4-train.*.npy}
  pad_direction: right
  num_workers: 4
  drop_last: true
  pin_memory: true
  prefetch_factor: 4  # bump to 16 if on LUMI
  persistent_workers: true
  timeout: 0

eval_interval: ${save_interval}
evaluators:
  - label: c4-validation
    device_eval_batch_size: ${device_train_microbatch_size}
    subset_num_batches: 5
    data:
      paths: ${path.glob:${path.choose:${oc.env:SCRATCH_DIR,no_exist}/pretraining_data/preprocessed,/net/nfs.cirrascale/allennlp/llm-data}/c4/en/c4-validation.*.npy}
      pad_direction: right
      num_workers: 4
      drop_last: true
      pin_memory: true
      prefetch_factor: 16
      persistent_workers: true
      timeout: 0

tokenizer:
  identifier: gpt2
  truncate_direction: right

save_folder: ${path.choose:${oc.env:SCRATCH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
save_interval: 500
save_interval_unsharded: 5000
save_num_checkpoints_to_keep: 3
save_num_unsharded_checkpoints_to_keep: -1
save_overwrite: false

load_path: null

max_duration: 3814697  # 2T tokens
global_train_batch_size: 512
device_train_microbatch_size: 16

precision: amp_bf16

max_grad_norm: 1.0

speed_monitor:
  window_size: 20

console_log_interval: 20
