run_name: pile-llamaish7-llama-tokenizer-001
seed: 6198
dry_run: false

wandb:
  name: ${run_name}
  project: olmo-medium
  group: pile-llamaish7-llama-tokenizer-001

model:
  d_model: 4096
  n_heads: 32
  n_layers: 32
  # mlp_ratio: 6
  mlp_hidden_size: 22016
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: false
  clip_qkv: 8.0
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 32000
  embedding_size: 32000
  eos_token_id: 2
  pad_token_id: 2
  init_device: meta
  init_fn: full_megatron
  init_std: 0.006
  init_cutoff_factor: 3

compile: null

optimizer:
  name: adamw
  learning_rate: 3.0e-4
  weight_decay: 0.1
  decay_norm_and_bias: true
  decay_embeddings: false
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  units: tokens
  t_warmup: 20971520000
  t_max: 3e12
  alpha_f: 0.1
  grad_clip_warmup_steps: 2097152000
  grad_clip_warmup_factor: 5

tokenizer:
  identifier: tokenizers/nousresearch-llama-2-7b-hf.json
  truncate_direction: right

save_folder: runs/${run_name}
remote_save_folder: s3://ai2-llm/checkpoints/OLMo-medium/${run_name}
save_overwrite: false

save_interval: 1000
save_interval_ephemeral: null
save_num_checkpoints_to_keep: -1
sharded_checkpointer: olmo_core

save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 2ep
global_train_batch_size: 512
device_train_microbatch_size: 2

precision: amp_bf16

fsdp:
  wrapping_strategy: by_block_and_size
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

eval_interval: 1000
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  - label: all-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        c4_en-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
        dolma_books-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_books/val/part-0-00000.npy
        dolma_common-crawl-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_common-crawl/val/part-0-00000.npy
        dolma_pes2o-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_pes2o/val/part-0-00000.npy
        dolma_reddit-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_reddit/val/part-0-00000.npy
        dolma_stack-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_stack/val/part-0-00000.npy
        dolma_wiki-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_wiki/val/part-0-00000.npy
        ice-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/ice/val/part-0-00000.npy
        m2d2_s2orc-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/m2d2_s2orc/val/part-0-00000.npy
        pile-validation:
        - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/pile/val/part-0-00000.npy
        wikitext_103-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/wikitext_103/val/part-0-00000.npy

  ##########################
  # Downstream evaluations #
  ##########################

  - label: hellaswag
    type: downstream


data:
  pad_direction: right
  num_workers: 32
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
    ######### PILE #########
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-00-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-01-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-02-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-03-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-04-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-05-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-06-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-07-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-08-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-09-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-10-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-11-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-12-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-13-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-14-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-15-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-16-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-17-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-18-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-19-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-20-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-21-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-22-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-23-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-24-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-25-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-26-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-27-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-28-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-29-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-30-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-31-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-32-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-33-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-34-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-35-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-36-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-37-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-38-00000.npy
    - s3://ai2-llm/preprocessed/pile/v0_decon_ppl_suite_v3_fixed/nousresearch-llama-2-7b-hf/part-39-00000.npy

